title: Aprendiendo git page
author: Josand23k
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Un curso para aprender a subir y modificar sites en github

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-cayman
